include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoDownloadBooks
AutoDownloadBooks_FILES = Switch.xm
AutoDownloadBooks_LIBRARIES = flipswitch
AutoDownloadBooks_PRIVATE_FRAMEWORKS = iTunesStore StoreServices
AutoDownloadBooks_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk