include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoDownloadMusic
AutoDownloadMusic_FILES = Switch.xm
AutoDownloadMusic_LIBRARIES = flipswitch
AutoDownloadMusic_PRIVATE_FRAMEWORKS = iTunesStore StoreServices
AutoDownloadMusic_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk