include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoDownloadUpdates
AutoDownloadUpdates_FILES = Switch.xm
AutoDownloadUpdates_LIBRARIES = flipswitch
AutoDownloadUpdates_PRIVATE_FRAMEWORKS = iTunesStore StoreServices
AutoDownloadUpdates_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk