include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AutoDownloadApps
AutoDownloadApps_FILES = Switch.xm
AutoDownloadApps_LIBRARIES = flipswitch
AutoDownloadApps_PRIVATE_FRAMEWORKS = iTunesStore StoreServices
AutoDownloadApps_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk